export const projects = [
  {
    id: 1,
    title: "Modular Automated Sorting Hub (M.A.S.H)",
    slug: "project-alpha",
    category: "Automation",
    description:
    "An AI-powered, cost-effective logistics solution designed to streamline package sorting through a scalable, modular system. By reducing costs to one-third of traditional sorting systems and enabling businesses to expand incrementally, MASH revolutionizes logistics with efficiency and flexibility.",
    features: [
      "6-axis movement with sub-millimeter precision",
      "Machine learning algorithms for adaptive task optimization",
      "Real-time feedback and adjustment system",
      "Modular end effectors for versatile applications",
      "Energy-efficient operation with power management",
    ],
    date: "August 2024",
    featured: true,
    link: "https://youtu.be/fjpFBquw1gs",
  },
  {
    id: 2,
    title: "Feathr",
    slug: "project-beta",
    category: "Development",
    description:
      "A comprehensive AI system designed for predictive maintenance in manufacturing environments, reducing downtime and optimizing operations.",
    features: [
      "Predictive analytics for equipment maintenance",
      "Real-time monitoring and anomaly detection",
      "Integration with existing industrial systems",
      "Customizable alert thresholds and notifications",
      "Historical data analysis and trend identification",
    ],
    date: "March 2025",
    featured: true,
    link: "https://example.com/project-beta",
  },
  {
    id: 3,
    title: "Becoming a Maker",
    slug: "project-gamma",
    category: "Media",
    description:
      "An end-to-end automation solution for warehouse management, featuring autonomous vehicles and intelligent inventory systems.",
    features: [
      "Fleet management for autonomous vehicles",
      "Real-time inventory tracking and optimization",
      "Intelligent routing and task allocation",
      "Integration with order management systems",
      "Scalable architecture for facilities of any size",
    ],
    date: "May 2023",
    featured: true,
    link: "https://example.com/project-gamma",
  },
  {
    id: 4,
    title: "Decipher",
    slug: "project-delta",
    category: "Media",
    description:
      "A collaborative robot designed to work alongside human operators in assembly lines, enhancing productivity while maintaining safety.",
    features: [
      "Advanced proximity sensors for human safety",
      "Intuitive programming interface for quick task setup",
      "Adaptive speed control based on environment",
      "Lightweight, portable design for flexible deployment",
      "Energy-efficient operation with extended battery life",
    ],
    date: "July 2023",
    featured: false,
    link: "https://example.com/project-delta",
  },
  {
    id: 5,
    title: "Gliogon",
    slug: "project-epsilon",
    category: "AI Systems",
    description:
      "A natural language processing system designed for technical support and customer service applications in the technology sector.",
    features: [
      "Domain-specific language understanding for technical queries",
      "Multi-language support for global deployment",
      "Integration with knowledge bases and documentation",
      "Continuous learning from interactions",
      "Seamless handoff to human agents when needed",
    ],
    date: "September 2023",
    featured: false,
    link: "https://example.com/project-epsilon",
  },
  {
    id: 6,
    title: "Project Zeta",
    slug: "project-zeta",
    category: "Automation",
    description:
      "A smart manufacturing system that optimizes production processes through real-time monitoring and adaptive control mechanisms.",
    features: [
      "Real-time production monitoring and analytics",
      "Adaptive process control for quality assurance",
      "Integration with supply chain management",
      "Energy consumption optimization",
      "Predictive maintenance for production equipment",
    ],
    date: "November 2023",
    featured: false,
    link: "https://example.com/project-zeta",
  },
]

